### ISSUE TITLE
no longer working in android 7...

### ISSUE THREAD

**Issue by loicsalou** [marcusasplund/ionic2-camera-demo#1]
Hi,

thanks for this demo, really nice and working up to android6.
Unfortunately with android7, which I have migrated to recently, it's now crashing.
I found some issue in apache cordova (https://issues.apache.org/jira/browse/CB-12370?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=15906293#comment-15906293) but the answer for now is just "no it's working", I'm pretty sure it's wrong.

when trying to use camera button I get en alert message 👍 
file:///storage/emulated/0/Android/data/com.ionicframework.graphlock548865/cache/.Pic.jpg exposed beyond app through ClipData.Item.getUri()

Any idea ? thanks !

**Comment by marcusasplund** [comment]
Hi @loicsalou 
Glad you've found it useful and a bummer that it is not working in Android 7. 
As you probably noticed i have not touched this demo in a year so i believe it could be severely outdated. I have no time until two weeks from now to start working on an updated version and looking into your issue. Until then it maybe best to browse and maybe drop a question in [ionic2 forum](https://forum.ionicframework.com/search?q=camera%20category%3A18%20order%3Alatest), there seems to be a lot of people with the same issue as yours.
Best, Marcus

**Comment by loicsalou** [comment]
Thanks for your answer.
I already did this and i have also created an issue in Cordova because it
seems to be the source of the problem. I will continue however to
investigate when I have time and I'll let you know any solution if I find
one.

Please let me know if you find anything before.
Thanks in advance.

Le dim. 19 mars 2017 à 16:28, Marcus Asplund <notifications@github.com> a
écrit :

**Comment by marcusasplund** [comment]
Bonjour!

Did a major rewrite reflecting the latest api, i believe i have got it working now, only tested in Android 7.1.1 on my Nexus 5x though.

**Comment by loicsalou** [comment]
Hi,

thanks for the effort, unfortunately the app is still crashing on my Galaxy s7 edge (android 7.0) when I try and use the button... as it was not workin I added an alert on error in the home.ts file, takePhoto method, in the (err) block and the error message is just the same as I have since I migrated to android 7...

I will dig a bit when I have time, dunno when, probably within a month.

**Comment by marcusasplund** [comment]
Hmm, that was sad. Maybe there is some issue with Android 7.0 then?
I've uploaded a build https://github.com/marcusasplund/ionic2-camera-demo/blob/master/android-debug.apk which you may please try out.
It is just this project; a button for taking a picture and uploading to ui.
I will probably delete it in some days.

**Comment by loicsalou** [comment]
Thanks a lot Markus, your APK works !
I think I understand where the problem comes from and I'll check very soon:
I suspect ionic-viewer to be the reason why I have this crash.

Will tell you.
Thanks !

Le mar. 4 avr. 2017 à 20:16, Marcus Asplund <notifications@github.com> a
écrit :

**Comment by marcusasplund** [comment]
Hope all goes well, glad i could help!

**Comment by loicsalou** [comment]
I can confirm: Camera plugin works fine when I build the apk and deploy it
on my android 7, but using the camera inside ionic-viewer crashes since
android 7.

Le mar. 4 avr. 2017 à 21:09, Marcus Asplund <notifications@github.com> a
écrit :

**Comment by marcusasplund** [comment]
Good to know for reference, hopefully the ionic-viewer gets fixed.
